version: '3.8'

services:
  redis:
    env_file:
      - ".env"
    image: "redis:5.0.4-stretch"
    volumes:
      - "redis:/data"

  web:
    build:
      context: "."
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - "redis"
    env_file:
      - ".env"
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:8000}:8000"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"

  worker:
    build:
      context: "."
    command: celery worker -A insurance --loglevel=info
    depends_on:
      - "redis"
    env_file:
      - ".env"
    volumes:
      - "${DOCKER_WEB_VOLUME:-./public:/app/public}"

volumes:
  redis: {}